# Generated by Django 4.2 on 2023-04-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook_app', '0002_class_course_student_dob_studentenrollment_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
    ]
